#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacobt-stedi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jacobt-stedi
  template:
    metadata:
      labels:
        app: jacobt-stedi
    spec:
      containers:
        - name: jacobt-stedi
          image: gcr.io/power-glove/stedi-jacobt:latest
          command: ["npm"]
          args: ["run", "start"]
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".2"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: jacobt-stedi-loadbalancer
spec:
  selector:
    app: jacobt-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000